#!/bin/sh

# Like append, but prefix the input with `\x1F` (Unit Separator) which
# acts as a separator.
input=$(xsel --output)
if [ -z $(xsel --output --secondary) ] ; then
    printf "\x1F$input" | xsel --input --secondary
else
    printf "\x1F$input" | xsel --append --secondary
fi
