#!/usr/bin/env perl

# Pop a value from secondary and put it in primary.
use strict;
use warnings;

my $secondary = `xsel --output --secondary`;
my $separator = "\x1F";

my @list = split("$separator", $secondary);

my $elem = pop @list;

# debug
print "elem: $elem";

# populate primary
`printf "$elem" | xsel --input`;

my $new_secondary = join("$separator", @list);
# populate secondary
`printf "$new_secondary" | xsel --input --secondary`;
