#!/usr/bin/env perl

# Pop a value from secondary and print it.
use strict;
use warnings;

my $secondary = `xsel --output --secondary`;
my constant $separator = "\x1F";

my @list = split("$separator", $secondary);

my $elem = pop @list;

my $new_secondary = join("$separator", @list);
# populate secondary
`printf "$new_secondary" | xsel --input --secondary`;

print "$elem"
